name: Playwright Tests

on: [push]

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  ui-chromium-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Chromium via docker-compose
        run: |
          docker compose run regression-chromium /bin/sh -c "ls -la && npm ci && npx playwright install && npx playwright test --config=ui.config.ts --project=chromium"

  ui-firefox-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Firefox tests via docker-compose
        run: |
          docker compose run regression-firefox /bin/sh -c "ls -la && npm ci && npx playwright install && npx playwright test --config=ui.config.ts --project=firefox"

  ui-webkit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Webkit tests via docker-compose
        run: |
          docker compose run regression-webkit /bin/sh -c "ls -la && npm ci && npx playwright install && npx playwright test --config=ui.config.ts --project=webkit"

  build-and-deploy-test-report:
    runs-on: ubuntu-latest
    needs: [ui-chromium-tests, ui-firefox-tests, ui-webkit-tests]
    steps:
      - name: Building report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploying report to GH page
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
