name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  HOME: /root

jobs:
  chromium-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-noble

    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: Run tests
        run: npm run tests:ui:chromium

  all-browsers-tests:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-noble
    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: Run tests
        run: npm run tests:ui:chromium

  building-report:
    needs: [chromium-tests, all-browsers-tests]
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-noble
    steps:
      - name: Collecting and building test report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

  Deploying-report-to-GH-page:
    needs: [building-report]
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-noble
    steps:
      - name: Deploying report to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
