name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  HOME: /root

jobs:
  chromium-tests:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: Install Java
        run: |
          apt-get update
          apt-get install -y openjdk-11-jdk

      - name: Check Java version
        run: java -version

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Check if allure-results exists
        run: |
          if [ ! -d "allure-results" ]; then
            echo "allure-results directory not found!";
            exit 1;
          fi

      - name: Run tests
        run: npx playwright test --config=ui.config.ts --project=chromium --output=allure-results

      - name: Generate report
        run: allure generate allure-results --clean -o allure-report

  all-browsers-tests:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.01-noble
    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run tests
        run: npm run tests:ui:chromium

      - name: Generate report
        run: allure generate allure-results --clean -o allure-report

  building-report:
    if: always()
    needs: [chromium-tests, all-browsers-tests]
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Collecting and building test report
        uses: simple-elf/allure-report-action@master
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

  deploying-report-to-GH-page:
    if: always()
    needs: [building-report]
    runs-on: ubuntu-latest
    steps:
      - name: Set Git safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploying report to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
