name: Playwright Tests

on: [push]

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  HOME: /root

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1-noble

    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: ui-chromium-tests
        run: npx playwright test --config=ui.config.ts --project=chromium

      - name: ui-firefox-tests
        run: npx playwright test --config=ui.config.ts --project=firefox

      - name: ui-webkit-tests
        run: npx playwright test --config=ui.config.ts --project=webkit

      - name: Generate report
        run: allure generate allure-results --clean -o allure-report

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Building report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploying report to GH page
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
