name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  HOME: /root

jobs:
  e2e-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}

      - name: Running tests on Chromium
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          "docker compose run e2e-ui-tests /bin/sh -c 
          ls -la 
          npm ci
          npx playwright install 
          npm run tests:ui:chromium"

      - name: Running tests on all browsers
        if: github.event_name == 'schedule'
        run: |
          docker compose run e2e-ui-tests /bin/sh -c 
          "ls -la 
          npm ci
          npx playwright install 
          npm run tests:ui:all"

      - name: Generate report
        run: allure generate allure-results --clean -o allure-report

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploying report to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: allure-history
