name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  HOME: /root

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1-noble

    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: ui-chromium-tests
        run: npm run tests:ui:chromium

      - name: ui-firefox-tests
        run: npm run tests:ui:firefox

      - name: ui-webkit-tests
        run: npm run tests:ui:webkit

      - name: Building report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploying report to GH page
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
