name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  e2e-ui-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN}}

      - name: Running tests on Chromium
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          docker compose run e2e-ui-tests /bin/sh -c "ls -la &&  npm run tests:ui:chromium && allure generate allure-results --clean -o allure-report"

      - name: Running tests on all browsers
        if: github.event_name == 'schedule'
        run: |
          docker compose run e2e-ui-tests /bin/sh -c "ls -la && npm run tests:ui:all && allure generate allure-results --clean -o allure-report"

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploying report to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()

        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
