name: Playwright Tests

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * 1-5"
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    BASE_URL: ${{ secrets.BASE_URL }}

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npx eslint .

            - name: Run Prettier
              run: npx prettier --check .

    e2e-ui-tests:
        runs-on: ubuntu-latest
        needs: lint-and-format
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout gh-pages branch (to restore history)
              uses: actions/checkout@v4
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Restore Allure history
              run: |
                  mkdir -p allure-results/history
                  if [ -d gh-pages/history ]; then
                    cp -r gh-pages/history allure-results/
                  fi

            - name: Set up Allure environment properties
              run: |
                  echo "BASE_URL=${{ secrets.BASE_URL }}" >> allure-results/environment.properties

            - name: Running tests on Chromium
              if: github.event_name == 'push' || github.event_name == 'pull_request'
              run: |
                  docker compose run e2e-ui-tests /bin/sh -c "ls -la \
                  && npm ci && npx playwright install && npm run tests:ui:chromium \
                  && allure generate allure-results --clean -o allure-report"

            - name: Running tests on all browsers
              if: github.event_name == 'schedule'
              run: |
                  docker compose run e2e-ui-tests /bin/sh -c "ls -la \
                  && npm ci && npx playwright install && npm run tests:ui:all \
                  && allure generate allure-results --clean -o allure-report"

            - name: Save Allure history
              run: |
                  mkdir -p allure-report/history
                  cp -r allure-results/history allure-report/

            - name: Build test report
              uses: simple-elf/allure-report-action@master
              if: always()
              id: allure-report
              continue-on-error: true
              with:
                  allure_results: allure-results
                  gh_pages: gh-pages
                  allure_report: allure-report
                  allure_history: allure-history
                  keep_reports: 20

            - name: Deploying report to GitHub pages
              uses: peaceiris/actions-gh-pages@v4
              if: always()
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: allure-history
