name: Playwright Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1-noble
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_URL: ${{ secrets.BASE_URL }}
      HOME: /root

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: Chromium tests
        run: npx playwright test --config=ui.config.ts --project=chromium --output=allure-results --shard=1/3

      - name: Firefox tests
        run: npx playwright test --config=ui.config.ts --project=firefox --output=allure-results --shard=2/3

      - name: Webkit tests
        run: npx playwright test --config=ui.config.ts --project=webkit --output=allure-results --shard=3/3

      - name: upload_allure_results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.shard }}
          path: allure-results/
          retention-days: 2

  merge_reports:
    runs-on: ubuntu-latest
    needs: [ui-tests]
    if: always()
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results/
          pattern: allure-results-*
          merge-multiple: true

      - name: Generate allure report
        run: npx allure generate allure-results

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
